### ISSUE TITLE
epic: Initial Echo Server Launch

### ISSUE THREAD

**Issue by HarryET** [WalletConnect/push-server#1]
Epic for initial launch of Echo Server, at this point it will have the same features as the old Push Server. At this point the code will be placed onto a branch as used for Coursework. Then the entire team can work on the project to improve with the additional features from the doc.

## Required
- [x] Register Clients
- [x] Unregister Clients
- [x] Accept Webhooks
- [x] CI/CD Pipeline
- [x] Relay Support (https://github.com/WalletConnect/rs-relay/pull/493)
- [x] Deployed instance (https://push.walletconnect.com)

## Nice to Have
- [x] Working telemetry
- [x] Link `telemetry` to `opentelemetry`

**Comment by arein** [comment]
Milestones suggestion:
* sample instance of echo server hosted for walletconnect e.g. `echo.walletconnect.com`
* Kotlin/Swift SDKs integrate it into their sample dapps and integration tests

**Comment by HarryET** [comment]
Milestones have been discussed internally and will be posted in slack.
