### ISSUE TITLE
feat: monitoring

### ISSUE THREAD

**Issue by HarryET** [WalletConnect/push-server#101]
Monitoring TODO list & nice to haves

```[tasklist]
### TODOs
- [ ] DB monitoring
- [ ] On Call Setup
- [ ] Add dashboards to terraform
```

```[tasklist]
### Nice to Haves
- [ ] Extra metrics e.g. FCM vs APNS
- [ ] Traces
```
