### ISSUE TITLE
fix: hardcode relay public key from environment variable

### ISSUE THREAD

**Issue by chris13524** [WalletConnect/push-server#228]
To validate incoming webhooks for pushed messages (push_message.rs), the echo server checks that the request is signed by the relay's public key (relay/mod.rs). To get the public key, it requests this from https://relay.walletconnect.com/public-key. However, the [logs show](https://walletconnect.slack.com/archives/C03SPNLG39P/p1695330354814059) that occasionally bursts of hundreds of "IncompleteMessage" errors performing this request occur, which results in the relay needing to retry sending of the webhook, and delayed PNs.

The cause of these errors is unknown, and has [also happened](https://walletconnect.slack.com/archives/C03SMNKLPU0/p1694704186740059) when the notify server attempts to use HTTP RPC method of publishing to the relay. But this appears to be a network-layer related issue when the connection is closed before a response is fully sent.

Some potential solutions to this could involve handling the errors gracefully, and using a stale public key in this case. As well as using a async lock to only allow 1 request to be in-flight at a time.

However, due to the nature that this public key is fixed, is the same across all relay nodes, and the plan for how these keys are managed across many relay instances involves a [GitHub repo](https://walletconnect.slack.com/archives/C05ABTQSPFY/p1692365559949539?thread_ts=1690988442.746529&cid=C05ABTQSPFY) as a registry of valid public keys, it is preferable to scrap the current implementation of requesting from `/public-key` and instead simply use an environment variable to provide the fixed public key.
```[tasklist]
### Tasks
- [ ] Scrap requesting logic
- [ ] Obtain public key by requesting it from https://relay.walletconnect.com/public-key
- [ ] Add environment variable and hardcode the public key in Terraform config
```
